### ISSUE TITLE
[BUG] K4System.ModuleTime

### ISSUE THREAD

**Issue by szogun1910** [K4ryuu/K4-System#108]
Css version: 142
Metamod:Source version 2.0.0-dev+1256

2024-01-07 19:19:40.284 +01:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'id')
   at CounterStrikeSharp.API.Modules.Entities.SteamID..ctor(UInt64 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs:line 13
   at K4System.ModuleTime.<>c__DisplayClass9_0.<SaveAllPlayerCache>b__1(CCSPlayerController player)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at K4System.ModuleTime.SaveAllPlayerCache(Boolean clear)
   at K4System.ModuleTime.<Initialize_Events>b__4_7(EventRoundEnd event, GameEventInfo info)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by K4ryuu** [comment]
Hello,
The reported problem has been fixed. This log is created by CounterStrikeSharp, when a player controller's SteamID64 is equals with 0. I blocked data save for players with no SteamID64 to prevent this warning log.

Appreciate your report!
