### ISSUE TITLE
[BUG] Cache - server crashing

### ISSUE THREAD

**Issue by csportalsk** [K4ryuu/K4-System#110]
```
[EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 2 not found in cache
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller) in C:\Users\mario\Documents\cs2\counterstrikesharp\counterstrikesharp-with-runtime-build-147-linux-204850f\addons\counterstrikesharp\source\K4-System\Plugin\PluginCache.cs:line 24
   at K4System.ModuleRank.<>c.<Initialize_Events>b__5_0(EventPlayerTeam event, GameEventInfo info) in C:\Users\mario\Documents\cs2\counterstrikesharp\counterstrikesharp-with-runtime-build-147-linux-204850f\addons\counterstrikesharp\source\K4-System\Module\Rank\RankEvents.cs:line 23
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

Log K4 - many rows like:
`[WARN] plugin:K4-System ModifyPlayerStats > Player is not loaded to the cache (PlayerName)`

Server crash. I tried CCS from v142 to v147. Builded plugin on v147 as you writed on Discord. Didn't help. Mos't crash on server with rounds.

**Comment by K4ryuu** [comment]
Greetings,
This problem has been fixed and will be published tonight after I finish the rest of the update.

Appreciate your time and issue.

Sincerely,
K4ryuu
