### ISSUE TITLE
[BUG] EventPlayerTeam warning logs

### ISSUE THREAD

**Issue by K4ryuu** [K4ryuu/K4-System#114]
This error wasn't fixed?
> [EROR] (cssharp:Core) Error invoking callback
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Collections.Generic.KeyNotFoundException: Player with ID 3 not found in cache
>    at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)
>    at K4System.ModuleRank.<>c.<Initialize_Events>b__5_0(EventPlayerTeam event, GameEventInfo info)
>    at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Delegate.DynamicInvokeImpl(Object[] args)
>    at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by mrdiega** [comment]
K4-System v3.1.1, css 154
```
Client 6 'крврпрыУПрарачон' signon state SIGNONSTATE_PRESPAWN -> SIGNONSTATE_SPAWN
STEAMAUTH: Client крврпрыУПрарачон received failure code 5
SV:  Disconnect client 'крврпрыУПрарачон' from server(15): NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
[EROR (cssharp:CoreError invoking callback[
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 6 not found in cache[
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)[
   at K4System.ModuleStat.SavePlayerStatCache(CCSPlayerController player, Boolean remove)[
   at K4System.ModuleStat.<>c__DisplayClass4_0.<Initialize_Events>b__9(EventPlayerDisconnect event, GameEventInfo info)[
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)[
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[
   --- End of inner exception stack trace ---[
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[
   at System.Delegate.DynamicInvokeImpl(Object[] args)[
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82[
05:09:34 WARN (plugin:[K4-System) [SavePlayerRankCache > Player is not loaded to the cache (крврпрыУПрарачон)[
Client 6 'крврпрыУПрарачон' signon state SIGNONSTATE_SPAWN -> SIGNONSTATE_NONE
SV:  Dropped client 'крврпрыУПрарачон' from server(15): NETWORK_DISCONNECT_STEAM_VAC_CHECK_TIMEDOUT
CloseSteamNetConnection handle #1019896876 (userdata 4)
```
