### ISSUE TITLE
[BUG] Error log to check

### ISSUE THREAD

**Issue by itsAudioo** [K4ryuu/K4-System#15]
I get this error log on both v50 and v52

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_12(EventRoundEnd event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 162
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81
   
   I don't know if this was reported allready

**Comment by K4ryuu** [comment]
Greetings,
I found the source of this harmless error log, and I have patched it. The new version will be available shortly.
