### ISSUE TITLE
[CRASH] Plugin will not load

### ISSUE THREAD

**Issue by Albo3** [K4ryuu/K4-System#177]
Cant get k4 to load for about a week
Tried reinstalls as well as trying to set it up on a fresh server

CSS was also not loading so I have done updates to get it working but now k4 is not loading

Logs:
css_plugins load K4-System
Could not load plugin "game\csgo\addons\counterstrikesharp\plugins/K4-System/K4-System.dll"
13:38:27 [EROR] (cssharp:Core) Could not load plugin "game\csgo\addons\counterstrikesharp\plugins/K4-System/K4-System.dll"
System.InvalidOperationException: Dependency resolution failed for component game\csgo\addons\counterstrikesharp\plugins/K4-System/K4-System.dll with error code -2147450734. Detailed error: Failed to locate managed application [game\csgo\addons\counterstrikesharp\plugins/K4-System/K4-System.dll]
   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at McMaster.NETCore.Plugins.Loader.ManagedLoadContext..ctor(String mainAssemblyPath, IReadOnlyDictionary`2 managedAssemblies, IReadOnlyDictionary`2 nativeLibraries, IReadOnlyCollection`1 privateAssemblies, IReadOnlyCollection`1 defaultAssemblies, IReadOnlyCollection`1 additionalProbingPaths, IReadOnlyCollection`1 resourceProbingPaths, AssemblyLoadContext defaultLoadContext, Boolean preferDefaultLoadContext, Boolean lazyLoadReferences, Boolean isCollectible, Boolean loadInMemory, Boolean shadowCopyNativeLibraries)
   at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.Build()
   at McMaster.NETCore.Plugins.PluginLoader..ctor(PluginConfig config)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Action`1 configure)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes, Action`1 configure)
   at CounterStrikeSharp.API.Core.Plugin.PluginContext..ctor(IServiceProvider applicationServiceProvider, ICommandManager commandManager, IScriptHostConfiguration hostConfiguration, String path, Int32 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 69
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 122
   at CounterStrikeSharp.API.Core.Application.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 177

- OS: [Windows OS]
- CSS Version [v223]
- K4-System Version [v4.2.0]

**Comment by K4ryuu** [comment]
“Detailed error: Failed to locate managed application “

Your CSS install fucked up most probably, so I recommend a PROPER install following the guide if CSS and K4-System. No problem reported like that.
