### ISSUE TITLE
[BUG] Config debug log blocks plugin load

### ISSUE THREAD

**Issue by cacaj** [K4ryuu/K4-System#21]
[ALoading plugin: K4System[1;36r[35;1H[1;35r[21S[14dFailed to load plugin /home/cs2/cs2-ds/game/csgo/addons/counterstrikesharp/plugins/K4-System/K4-System.dll with error System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at K4ryuuSystem.K4System.Log(String message, LogLevel level, Boolean hotReload) in C:\Users\Rinas\Desktop\K4-System-1.3.0\src\Logs.cs:line 21
   at K4ryuuSystem.K4System.OnConfigParsed(MyConfig config) in C:\Users\Rinas\Desktop\K4-System-1.3.0\src\Configs.cs:line 234
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 354
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/PluginContext.cs:line 107
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 97
   at CounterStrikeSharp.API.Core.GlobalContext.LoadAllPlugins() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 136

**Comment by mrdiega** [comment]
It won't start for me either
```
css_plugins load K4-System
Loading plugin: K4System
Failed to load plugin /home/servermiragecs2/steamcmd/server/game/csgo/addons/counterstrikesharp/plugins/K4-System/K4-System.dll with error System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at K4ryuuSystem.K4System.Log(String message, LogLevel level, Boolean hotReload) in /Users/sples/Documents/GitHub/K4-System/src/Logs.cs:line 21
   at K4ryuuSystem.K4System.OnConfigParsed(MyConfig config) in /Users/sples/Documents/GitHub/K4-System/src/Configs.cs:line 234
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 354
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/PluginContext.cs:line 107
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 97
   at CounterStrikeSharp.API.Core.GlobalContext.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 260
```
K4-System v1.3.0
counterstrikesharp-build-53-linux-0ddf6bc
metamod 2.0 - build 1266

**Comment by cacaj** [comment]
**Problem fixed**,  _just change line_ **15** _on_ **K4-System.cs**
`15. public int ModuleConfigVersion => 2; ` 
to this 
`15. public int ModuleConfigVersion => 1;`

![Screenshot 2023-11-17 022925](https://github.com/K4ryuu/K4-System/assets/120527547/371635ce-8666-4047-82cd-f1bffd542066)


**Then compile file running on terminal**

`dotnet build`

**_Or simply download the_ DLL _file_** [here](https://cacaj.site/K4-System.dll) _and replace to_ plugins directory

> ../plugins/K4-System/

**Comment by mrdiega** [comment]
With fix from @cacaj, the plugin started
1) round-end-points still does not work, points are not awarded for winning a round
2) Messages about awarding points for each action are missing
3) Messages about scoring only work when spawn-message is true, but only displays the total number. I don’t need a message from the plugin every round; in 1.2.0 version it worked more correctly.
4) This message often appears in the console: "[INFO] > Points are not allowed."

**Comment by K4ryuu** [comment]
The next release will contains the bug patch, when I upload it.
