### ISSUE TITLE
[BUG] !rank command

### ISSUE THREAD

**Issue by AZzeLx** [K4ryuu/K4-System#26]
This error appears only when I execute the !rank command.

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> MySqlConnector.MySqlException (0x80004005): Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation '='
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 344
   at MySqlConnector.MySqlCommand.ExecuteReader() in /_/src/MySqlConnector/MySqlCommand.cs:line 112
   at Nexd.MySQL.MySqlDb.<>c__DisplayClass36_0.<ExecuteQueryInternal>b__0(MySqlConnection connection)
   at Nexd.MySQL.MySqlDb.CreateContext[T](Func`2 context)
   at K4ryuuSystem.K4System.GetPlayerPlaceAndCount(String playerName) in /Users/sples/Documents/GitHub/K4-System/src/Functions.cs:line 244
   at K4ryuuSystem.K4System.OnCommandCheckRank(CCSPlayerController player, CommandInfo command) in /Users/sples/Documents/GitHub/K4-System/src/Commands.cs:line 62
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 196
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81`

**Comment by asdfxD** [comment]
same here, probably that's the reason my !rank was not working, did not checked console.

**Comment by K4ryuu** [comment]
@AZzeLx do you have a '=' symbol in your MySQL password?

**Comment by AZzeLx** [comment]
> @AZzeLx do you have a '=' symbol in your MySQL password?

No, my password:  "password": "r7&Nd.R7.}xE",

**Comment by K4ryuu** [comment]
Most probably I have found the problem.
The possible patch will be available in the next release and I ask you gently to close the issue if you find this problem solved.

I will push the release shortly.

Thank you for the feedback!

**Comment by AZzeLx** [comment]
Solved!
