### ISSUE TITLE
server crash when using !ranktop or !top5 etc

### ISSUE THREAD

**Issue by ry1nffx11** [K4ryuu/K4-System#27]
--- End of stack trace from previous location ---
at Nexd.MySQL.MySqlDb.CreateContextAsync[T](Func`2 asyncContext)
at Nexd.MySQL.MySqlDb.ExecuteQueryInternalAsync(String query)
at Nexd.MySQL.MySqlDb.ExecuteQueryAsync(String statement)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[39;49m[39;49m[40m[39;49m[36m[40mMySqlConnector.MySqlException (0x80004005): Table 'gamersnest_ranks.k4ranks' doesn't exist
at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 966
at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 344
at Nexd.MySQL.MySqlDb.<>c__DisplayClass37_0.<<ExecuteQueryInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Nexd.MySQL.MySqlDb.CreateContextAsync[T](Func`2 asyncContext)
at Nexd.MySQL.MySqlDb.ExecuteQueryInternalAsync(String query)
at Nexd.MySQL.MySqlDb.ExecuteQueryAsync(String statement)
at K4ryuuSystem.K4System.PrintTopXPlayers(CCSPlayerController player, Int32 number) in /Users/sples/Documents/GitHub/K4-System/src/Functions.cs:line 91
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[39;49mUnhandled exception. MySqlConnector.MySqlException (0x80004005): Table 'gamersnest_ranks.k4ranks' doesn't exist
at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 966
at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 344
at Nexd.MySQL.MySqlDb.<>c__DisplayClass37_0.<<ExecuteQueryInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Nexd.MySQL.MySqlDb.CreateContextAsync[T](Func`2 asyncContext)
at Nexd.MySQL.MySqlDb.ExecuteQueryInternalAsync(String query)
at Nexd.MySQL.MySqlDb.ExecuteQueryAsync(String statement)
at K4ryuuSystem.K4System.PrintTopXPlayers(CCSPlayerController player, Int32 number) in /Users/sples/Documents/GitHub/K4-System/src/Functions.cs:line 91
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by K4ryuu** [comment]
Greetings,
You should check that instead of the commands, that why the tables not getting generated at you. 

Probably you'll find some errors about that.

**Comment by K4ryuu** [comment]
As the user stated on Discord, was able to solve the solution by upgrading CSSharp version.
