### ISSUE TITLE
[BUG] With K4ryuuDamageInfo v1.3.3 server crash

### ISSUE THREAD

**Issue by csportalsk** [K4ryuu/K4-System#38]
I tried new release v1.3.3. New DB, CSSharp v65, Metamod:Source version 2.0.0-dev+1270. 
It works and some error from console.

```
20:17:56 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at K4ryuu.GameRules() in /Users/sples/Documents/GitHub/K4-System/src/K4ryuuHelpers.cs:line 16
   at K4ryuuSystem.K4System.IsPointsAllowed() in /Users/sples/Documents/GitHub/K4-System/src/Functions.cs:line 482
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_11(EventRoundStart event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 243
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 71
```

**But when you have new release K4ryuuDamageInfo v1.3.3 server crash with** `Segmentation fault`. K4ryuuDamageInfo v1.3.3 without [K4-System] works and server doesn't crash.

**Comment by csportalsk** [comment]
The problem was K4ryuuDamageInfo v1.3.2 and temporarily "fix" after map change stop works, with css_plugins reload #idplugin .cfg.
_Can be closed._

**Comment by K4ryuu** [comment]
For the K4 site I fixed the problem, however it needs to be changed also in the DamageInfo side too later on maybe. You can test in the next patch.
