### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#50]
K4-System v1.3.3
css v65
```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Nullable object must have a value.
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_17(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 571
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
20:13:36 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Nullable object must have a value.
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_17(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 571
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```
I don't know why, but this sometimes appears in the console

**Comment by K4ryuu** [comment]
Greetings,
I have fixed this problem and being uploaded in the next patch (1.3.4).
Thank you for the report.
