### ISSUE TITLE
[BUG] [EROR] (cssharp:Core) Error invoking callback  > SERVER CRASH

### ISSUE THREAD

**Issue by jinnixyz** [K4ryuu/K4-System#52]
If you change teams while you are alive and die (suicide) you get this error message in the console. If you do this 4-5 times in a row, the server crashes. No ranking points are deducted for suicide. Before Server Crash in chat appears this : SEE SCREENSHOT

![SERVER CRASH](https://github.com/K4ryuu/K4-System/assets/89946984/10f57f58-6803-4657-9633-d8402b0f18fd)
![server crash 2](https://github.com/K4ryuu/K4-System/assets/89946984/e595447b-0b86-4ef3-a35e-387f8cc5934f)

EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Collections.Generic.KeyNotFoundException: The given key 'deaths' was not present in the dictionary.
at K4ryuuSystem.K4System.<SetupGameEvents>b__18_18(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 426
at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by K4ryuu** [comment]
Are you using any accelerator plugin?

**Comment by jinnixyz** [comment]
No, I think it's because if you take control of a bot with E and then commit suicide (teamchange), the ranking system doesn't recognize the type of death, hence Event Death Player? You also don't get any points for suicide

**Comment by K4ryuu** [comment]
My Discord community currently tests 1.3.5 version, which may be fixed this problem. If all test are good, you will see the patches shortly.
