### ISSUE TITLE
[BUG] Bug after changing map

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#54]
K4-System V1.3.4
counterstrikesharp-build-71-linux-7e9e7c6

After changing the map, some players may have their rank reset to Silver 1
![1 3 4 brago](https://github.com/K4ryuu/K4-System/assets/79888956/59c28d57-d0cb-4db6-a741-c43b9f704a48)
![1 3 4  2](https://github.com/K4ryuu/K4-System/assets/79888956/6b103a45-0419-417f-9b91-19d380284b85)

but their rank remains in the database. 
![1 3 4](https://github.com/K4ryuu/K4-System/assets/79888956/8c1c5a6b-e729-4dca-8dc2-9354c51c753b)
If the player reconnect to server, the rank is returned

Errors in the console:
```
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'deaths' was not present in the dictionary.
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_18(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 426
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
17:58:38 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'deaths' was not present in the dictionary.
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_18(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 426
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 381] removing change '3/7/50' for field m_PredNetByteVariables[50] (value '0') on array that has metadata with only 50 array elements!
```

This problem appeared after updating from version 1.3.3 to version 1.3.4

upd. 
I also forgot to say that the `spawn-message` variable turns off not only messages during spawn, but also all messages from the plugin in general, this is wildly inconvenient.

**Comment by K4ryuu** [comment]
Greetings,
Thank you for the feedback. We are testing the solution currently.
