### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#59]
K4-System V1.3.4
counterstrikesharp-build-77-linux-319b116

Server crash after several hours of working with players

![crash](https://github.com/K4ryuu/K4-System/assets/79888956/7172ad87-cfd1-4ea8-a8ae-a597b1f901ae)
```
2023-11-27 21:12:30 [INFO] > Stats are allowed.
2023-11-27 21:12:30 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Points are allowed.
2023-11-27 21:12:31 [INFO] > Points are allowed.
2023-11-27 21:12:31 [INFO] > Points removed (-1) for HoTaRo.
2023-11-27 21:12:31 [INFO] > Stats are allowed.
2023-11-27 21:12:31 [INFO] > Points are allowed.
2023-11-27 21:12:31 [INFO] > Points are allowed.
2023-11-27 21:12:31 [INFO] > Points added (+6) for ㊗爪丨尺卂Ꮆ乇㊗.
2023-11-27 21:12:31 [INFO] > Points are allowed.
2023-11-27 21:12:31 [INFO] > Points added (+2) for ㊗爪丨尺卂Ꮆ乇㊗.
2023-11-27 21:12:37 [INFO] > Stats are allowed.
2023-11-27 21:12:37 [INFO] > Stats are allowed.
2023-11-27 21:12:37 [INFO] > Points are allowed.
2023-11-27 21:12:37 [INFO] > Points are allowed.
2023-11-27 21:12:37 [INFO] > Points removed (-1) for ㊗爪丨尺卂Ꮆ乇㊗.
2023-11-27 21:12:37 [INFO] > Stats are allowed.
2023-11-27 21:12:37 [INFO] > Points are allowed.
2023-11-27 21:12:37 [INFO] > Points are allowed.
2023-11-27 21:12:37 [INFO] > Points added (+6) for пулемётчик36.
2023-11-27 21:12:37 [INFO] > Kill streak reset for player at index 1296.
2023-11-27 21:12:37 [INFO] > Points are allowed.
2023-11-27 21:12:37 [INFO] > Points are allowed.
2023-11-27 21:12:37 [INFO] > Points added (+1) for HoTaRo.
RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 874] removing change '3/12/112                                                                                                                                         ' for field m_PredNetFloatVariables[112] (value '2.03125') on array that has metadata with only 106                                                                                                                                          array elements!
2023-11-27 21:12:37 [INFO] > Stats are allowed.
[All Chat][Lomik (59243653)]: !rank
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an ob                                                                                                                                         ject.
   at K4ryuuSystem.K4System.OnCommandCheckRank(CCSPlayerController player, CommandInfo command) in /                                                                                                                                         Users/sples/Documents/GitHub/K4-System/src/Commands.cs:line 66
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aborted (core dumped)
```

**Comment by K4ryuu** [comment]
Greetings,
I am going to check the problem shortly
