### ISSUE TITLE
[REQ] Hello after counterstrikesharp update 

### ISSUE THREAD

**Issue by sidasltu** [K4ryuu/K4-System#65]
after this morning update k4 cant be loading in server
12:02:23 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/K4-System/K4-System.dl

**Comment by mrc4tt** [comment]
It will be an advantage if you present more information on it.

**Comment by sidasltu** [comment]
> It will be an advantage if you present more information on it.

This morning i update counterstrikesharp  to the new version its realised just today and after that i restart server and get error that k4 system cannot be loading anymore .



12:07:50 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/K4-System/K4-System.dll
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at CounterStrikeSharp.API.Core.Plugin.PluginContext..ctor(IServiceProvider applicationServiceProvider, IScriptHostConfiguration hostConfiguration, String path, Int32 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 84
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 50
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginMana

**Comment by mrc4tt** [comment]
I can't reproduce it. It loads fine here, it looks like your provider has a limitation (without being 100% sure)

You need to contact your GSP:
`The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.`

**Comment by K4ryuu** [comment]
Greetings,
I close every issue, because 2.0 is released and no idea what is a current problem.
