### ISSUE TITLE
[BUG] no points when winning round and losing round

### ISSUE THREAD

**Issue by mrdiega** [K4ryuu/K4-System#7]
"K4-System" (v1.2.0) by K4ryuu
counterstrikesharp-build-50-linux-414710d

console error
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '5' was not present in the dictionary.
   at K4ryuuSystem.K4System.<SetupGameEvents>b__18_17(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/K4-System/src/Events.cs:line 254
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81
```

**Comment by K4ryuu** [comment]
Greetings,
The reported error was about EventPlayerDeath event, because the killer was not properly loaded at some point. I have fixed this log. The new version will be released shortly upon all problems solved.

Thank you for using GitHub issues to report the bug and thank you for your feedback!

Best Regards,
K4ryuu
