### ISSUE TITLE
[BUG] Module time

### ISSUE THREAD

**Issue by skaen** [K4ryuu/K4-System#75]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 17 not found in cache
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)
   at K4System.ModuleTime.<Initialize_Events>b__4_6(EventPlayerDisconnect event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

```

**Comment by K4ryuu** [comment]
Greetings,
Gonna check it shortly Today.
Thank you

**Comment by K4ryuu** [comment]
The issue has been resolved and is scheduled for release in the upcoming version (V2.0.2), provided that all other outstanding issues are successfully addressed.
