### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by scorp1onul** [K4ryuu/K4-System#90]
Hello. I receive these 2 errors at some hours and crash also. Without K4 no crash since 2 days. I tested the system on server with 30+ online players if it help this information

```css
2023-12-21 11:33:23.774 +02:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 21 not found in cache
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)
   at K4System.ModuleRank.SavePlayerRankCache(CCSPlayerController player, Boolean remove)
   at K4System.ModuleRank.<Initialize_Events>b__5_15(EventPlayerDisconnect event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

```

And also this in the same time

```css
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 21 not found in cache
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)
   at K4System.ModuleStat.SavePlayerStatCache(CCSPlayerController player, Boolean remove)
   at K4System.ModuleStat.<Initialize_Events>b__4_8(EventPlayerDisconnect event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

```

After crash i have a new logs with local data not loaded.
![b70c77d8-5f92-4905-bc81-72a6ba49fbfa](https://github.com/K4ryuu/K4-System/assets/107995301/9947b2dc-8dd7-4692-aeed-4472eed1fa49)

**Comment by K4ryuu** [comment]
Greetings,
Could you send me one of your CSS "all" log file from a day when you have experienced a crash?

**Comment by skaen** [comment]
@K4ryuu  
[log-all20231227.txt](https://github.com/K4ryuu/K4-System/files/13779401/log-all20231227.txt)

**Comment by K4ryuu** [comment]
Greetings,
This problem is because the plugin missing some of the fields most probably. Try the newest pre release version, which is going to show you these problems.

**Comment by skaen** [comment]
@K4ryuu last version k4

```
2023-12-29 08:43:40.866 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 0 not found in cache
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)
   at K4System.ModuleStat.SavePlayerStatCache(CCSPlayerController player, Boolean remove)
   at K4System.ModuleStat.<Initialize_Events>b__4_10(EventPlayerDisconnect event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
2023-12-29 08:43:40.870 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Player with ID 0 not found in cache
   at K4System.PlayerCache`1.get_Item(CCSPlayerController controller)
   at K4System.ModuleRank.SavePlayerRankCache(CCSPlayerController player, Boolean remove)
   at K4System.ModuleRank.<>c__DisplayClass5_0.<Initialize_Events>b__15(EventPlayerDisconnect event, GameEventInfo info)
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
   ```
